config:
  server:
    student-key: Hello, from Config Server

spring:
  data:
    cassandra:
      keyspace-name: student_service
      port: 9042
      contact-points: localhost
      username: cassandra
      password: cassandra